export const sampleData = [
  {
    date: "03-10-2025",
    client: "Xtream Media",
    batch: "DX128",
    lot: 7,
    type: "IN",
    qty: 200,
    reason: "",
    rcdc: "Tran Date",
    remarks: "",
  },
  {
    date: "05-12-2025",
    client: "Xtream Media",
    batch: "DX128",
    lot: 7,
    type: "DISPATCH",
    qty: 37,
    reason: "",
    rcdc: "DC9",
    remarks: "",
  },
  {
    date: "20-11-2025",
    client: "Xtream Media",
    batch: "DX128",
    lot: 8,
    type: "IN",
    qty: 200,
    reason: "",
    rcdc: "Tran Date",
    remarks: "",
  },
  {
    date: "20-11-2025",
    client: "Xtream Media",
    batch: "DX214",
    lot: 9,
    type: "IN",
    qty: 10,
    reason: "",
    rcdc: "Tran Date",
    remarks: "",
  },
  {
    date: "13-12-2025",
    client: "Xtream Media",
    batch: "DX214",
    lot: 9,
    type: "DISPATCH",
    qty: 10,
    reason: "",
    rcdc: "DC10",
    remarks: "",
  },
  {
    date: "05-12-2025",
    client: "Xtream Media",
    batch: "DX214",
    lot: 10,
    type: "IN",
    qty: 40,
    reason: "",
    rcdc: "Tran Date",
    remarks: "",
  },
  {
    date: "13-12-2025",
    client: "Xtream Media",
    batch: "DX214",
    lot: 10,
    type: "DISPATCH",
    qty: 5,
    reason: "",
    rcdc: "DC11",
    remarks: "",
  },
  {
    date: "05-12-2025",
    client: "Xtream Media",
    batch: "DX128",
    lot: 4,
    type: "REPAIR_DISPATCH",
    qty: 33,
    reason: "",
    rcdc: "",
    remarks: "",
  },
  {
    date: "05-12-2025",
    client: "Xtream Media",
    batch: "DX128",
    lot: 6,
    type: "REPAIR_DISPATCH",
    qty: 26,
    reason: "",
    rcdc: "",
    remarks: "",
  },
  {
    date: "05-12-2025",
    client: "Xtream Media",
    batch: "DX128",
    lot: 4,
    type: "DISPATCH",
    qty: 20,
    reason: "",
    rcdc: "DC12",
    remarks: "",
  },
  {
    date: "05-12-2025",
    client: "Xtream Media",
    batch: "DX128",
    lot: 6,
    type: "DISPATCH",
    qty: 34,
    reason: "",
    rcdc: "DC13",
    remarks: "",
  },
  {
    date: "13-12-2025",
    client: "Xtream Media",
    batch: "DX214",
    lot: 11,
    type: "IN",
    qty: 15,
    reason: "",
    rcdc: "Tran Date",
    remarks: "",
  },
];

export const header = [
  "Tran Date",
  "Client",
  "Batch No",
  "Lot No",
  "Tran Type",
  "Qty",
  "Return Reason",
  "RC/DC No",
  "Remarks",
];
